#!/bin/sh

battery=$(cat /sys/class/power_supply/BAT*/capacity 2>/dev/null | head -n1)
status=$(cat /sys/class/power_supply/BAT*/status 2>/dev/null | head -n1)

[ -z "$battery" ] && exit

if [ "$status" = "Charging" ]; then
    icon="󰂄"
elif [ "$battery" -ge 90 ]; then
    icon="󰁹"
elif [ "$battery" -ge 70 ]; then
    icon="󰂀"
elif [ "$battery" -ge 50 ]; then
    icon="󰁾"
elif [ "$battery" -ge 30 ]; then
    icon="󰁼"
elif [ "$battery" -ge 10 ]; then
    icon="󰁺"
else
    icon="󰂃"
fi

printf '%s %s%%' "$icon" "$battery"
