#!/bin/sh

volume=$(pactl get-sink-volume @DEFAULT_SINK@ | awk 'NR==1 {print $5}')
mute=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')

if [ "$mute" = "yes" ]; then
    printf '󰖁 Muted'
else
    printf '󰕾 %s' "$volume"
fi
